version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
  express-api-es6-starter:
    build: ./
    volumes:
      - .env.docker:/app/.env
    ports:
      - "8848:8848"
    entrypoint: /bin/sh
    command: -c "sleep 5 && yarn migrate && yarn seed && yarn start:dev"
    depends_on:
      - db
    links:
      - db
volumes:
    db_data:
